language: node_js
node_js:
- 6.9.5
- 7.5.0
before_script: npm install
script: npm start
before_install:
- openssl aes-256-cbc -K $encrypted_ee748c561b50_key -iv $encrypted_ee748c561b50_iv -in id_rsa.enc -out ~\/.ssh/id_rsa -d

